Fix some compilation errors (#30)
Fixes the following compilation errors:

 rialto/ipc/client/source/IpcChannelImpl.cpp:601:29:
 error: suggest braces around initialization of subobject
  [-Werror,-Wmissing-braces]
    struct itimerspec ts = {0};
                            ^
                            {}

 rialto/media/server/main/source/SharedMemoryBuffer.cpp:159:40:
 error: lambda capture 'sessionId' is not used
  [-Werror,-Wunused-lambda-capture]
   [sessionId](const auto &p) { return p.sessionId == NO_SESSION_ASSIGNED; });
    ^~~~~~~~~

 rialto/media/common/include/MediaFrameWriterV2.h:64:14:
  error: 'getNumFrames' overrides a member function but is not marked 'override'
   [-Werror,-Winconsistent-missing-override]
    uint32_t getNumFrames() { return m_numFrames; }
             ^

 rialto/media/server/gstplayer/source/tasks/FinishSetupSource.cpp:91:87:
  error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
   GstAppSrcCallbacks callbacks = {appSrcNeedData, appSrcEnoughData, appSrcSeekData,
    nullptr};
    ^~~~~~~
    {      }

 rialto/media/server/gstplayer/include/tasks/Shutdown.h:28:1:
  error: struct 'IGstPlayerPrivate' was previously declared as a class;
   this is valid, but may result in linker errors under the Microsoft C++ ABI
   [-Werror,-Wmismatched-tags]
   struct IGstPlayerPrivate;
   ^
  media/server/gstplayer/include/IGstPlayerPrivate.h:29:7: note: previous use is here
  class IGstPlayerPrivate
  ^

  media/server/gstplayer/include/tasks/SetPosition.h:43:24:
   error: private field 'm_player' is not used [-Werror,-Wunused-private-field]
    IGstPlayerPrivate &m_player;
                       ^

 media/server/gstplayer/include/GstWrapper.h:289:10:
  error: 'gstByteWriterInitWithData' overrides a member function but is not marked
  'override' [-Werror,-Winconsistent-missing-override]
  void gstByteWriterInitWithData(GstByteWriter *writer, guint8 *data, ...
       ^

 media/server/gstplayer/include/IGstWrapper.h:716:18: note: overridden virtual function
    virtual void gstByteWriterInitWithData(GstByteWriter *writer, guint8 *data, ...
                 ^

 tests/media/server/main/dataReader/DataReaderV2Tests.cpp:49:20:
  error: unused variable 'kMediaKeysId' [-Werror,-Wunused-const-variable]
   constexpr uint32_t kMediaKeysId{54354};
                      ^
 tests/media/server/main/mediaPipelineCapabilities/MediaPipelineCapabilitiesTest.cpp:53:37:
  error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
   .WillOnce(Return(ByMove(std::move(std::unique_ptr<firebolt::rialto::server::IGstCapabilities>()))));
                           ^

 rialto/rialto/tests/media/server/main/mediaPipelineCapabilities/MediaPipelineCapabilitiesTest.cpp:53:37:
  note: remove std::move call here
   .WillOnce(Return(ByMove(std::move(std::unique_ptr<firebolt::rialto::server::IGstCapabilities>()))));
                           ^~~~~~~~~~                                                             ~

  tests/media/server/main/mediaKeysCapabilities/KeySystemsTest.cpp:47:38: error:
   implicit instantiation of undefined template 'std::array<std::basic_string<char>, 3>'
    const std::array<std::string, 3> m_supportedKeySystems{"com.widevine.alpha", "com.microsoft.playready",
                                     ^

  tests/media/server/main/sharedMemoryBuffer/SharedMemoryBufferTestsFixture.cpp:24:15:
   error: unused variable 'maxPlaybacks' [-Werror,-Wunused-const-variable]
   constexpr int maxPlaybacks{1};
                 ^
  tests/media/server/main/needMediaData/NeedMediaDataTestsFixture.cpp:35:15:
   error: unused variable 'maxMediaBytes' [-Werror,-Wunused-const-variable]
   constexpr int maxMediaBytes{7337532};
                 ^

  rialto/tests/media/server/gstplayer/player/tasksTests/AttachSamplesTest.cpp:36:18:
   error: unused variable 'currentTimestamp' [-Werror,-Wunused-const-variable]
    constexpr gint64 currentTimestamp = 2340538204;
                     ^

  tests/media/server/gstplayer/player/tasksTests/ReadShmDataAndAttachSamplesTest.cpp:38:18:
   error: unused variable 'currentTimestamp' [-Werror,-Wunused-const-variable]
    constexpr gint64 currentTimestamp = 2340538204;
                     ^

  tests/media/server/mocks/gstplayer/GstWrapperMock.h:181:19:
   error: 'gstStructureNew' overrides a member function but is not marked 'override'
    [-Werror,-Winconsistent-missing-override]
     GstStructure *gstStructureNew(const gchar *name, const gchar *firstfield, ...) const
                   ^

  media/server/ipc/source/MediaPipelineModuleService.cpp:112:10: error:
   comparison of different enumeration types in switch statement
   ('firebolt::rialto::AttachSourceRequest_StreamFormat' and
    'firebolt::rialto::AttachSourceRequest_SegmentAlignment') [-Werror, -Wenum-compare-switch]
    case firebolt::rialto::AttachSourceRequest_SegmentAlignment_ALIGNMENT_UNDEFINED:
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--
Summary: Fix some compilation errors
Type: fix
Owner: Damian Wrobel
Test Plan: Unit Tests